"use client"

import { useState, useEffect } from "react"
import Link from "next/link"
import { Play, Trophy, Users, Coins, Brain, Zap, Shield, TrendingUp, ChevronRight, Star, Award } from "lucide-react"
import { Navigation } from "@/components/navigation"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"

const stats = [
  { label: "Active Players", value: "12,847", icon: Users, color: "text-primary-400" },
  { label: "HBAR Distributed", value: "₪ 45,230", icon: Coins, color: "text-accent-500" },
  { label: "Questions Available", value: "50,000+", icon: Brain, color: "text-purple-400" },
  { label: "Daily Rewards", value: "₪ 2,150", icon: Trophy, color: "text-yellow-400" },
]

const features = [
  {
    icon: Brain,
    title: "AI-Powered Questions",
    description: "Dynamic trivia questions generated by ChatGPT across multiple categories and difficulty levels.",
    color: "text-primary-400",
  },
  {
    icon: Coins,
    title: "Earn HBAR Rewards",
    description: "Get rewarded with real HBAR tokens for correct answers and maintaining winning streaks.",
    color: "text-accent-500",
  },
  {
    icon: Trophy,
    title: "Competitive Leaderboards",
    description: "Climb the global rankings and compete with players worldwide for the top spots.",
    color: "text-yellow-400",
  },
  {
    icon: Shield,
    title: "Secure & Transparent",
    description: "Built on Hedera network ensuring fast, secure, and transparent gameplay.",
    color: "text-purple-400",
  },
  {
    icon: Zap,
    title: "Real-time Gameplay",
    description: "Instant feedback, live scoring, and seamless gaming experience across all devices.",
    color: "text-pink-400",
  },
  {
    icon: TrendingUp,
    title: "Performance Analytics",
    description: "Track your progress with detailed statistics and performance insights.",
    color: "text-blue-400",
  },
]

export default function HomePage() {
  const [currentStat, setCurrentStat] = useState(0)

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentStat((prev) => (prev + 1) % stats.length)
    }, 3000)
    return () => clearInterval(interval)
  }, [])

  return (
    <div className="min-h-screen bg-dark-gradient">
      <Navigation />

      {/* Hero Section */}
      <section className="relative pt-20 pb-16 overflow-hidden">
        {/* Animated Background Elements - REMOVED */}
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <div className="mb-8 animate-fade-in">
              <h1 className="text-4xl md:text-6xl lg:text-7xl font-cyber font-bold mb-6">
                <span className="text-gradient">HashQuest</span>
                <br />
                <span className="text-white text-2xl md:text-4xl lg:text-5xl">The Ultimate Blockchain Trivia</span>
              </h1>
              <p className="text-xl md:text-2xl text-gray-300 max-w-3xl mx-auto leading-relaxed">
                Challenge your knowledge, earn HBAR rewards, and compete with players worldwide in the most
                sophisticated trivia game on the Hedera network.
              </p>
            </div>

            <div className="flex flex-col sm:flex-row gap-4 justify-center items-center mb-16 animate-slide-up">
              <Link href="/auth/signup">
                <Button
                  size="lg"
                  className="sophisticated-button cyber-gradient text-lg px-8 py-4 hover:shadow-xl hover:shadow-primary-500/25 group"
                >
                  <Play className="w-6 h-6 mr-2 group-hover:scale-110 transition-transform" />
                  Start Playing Now
                  <ChevronRight className="w-5 h-5 ml-2 group-hover:translate-x-1 transition-transform" />
                </Button>
              </Link>
              <Link href="/connect-wallet">
                <Button
                  variant="outline"
                  size="lg"
                  className="bg-purple-gradient text-white text-lg px-8 py-4 hover:shadow-xl hover:shadow-purple-500/25 group"
                >
                  Connect Wallet
                </Button>
              </Link>
            </div>

            {/* Animated Stats */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-6 max-w-4xl mx-auto animate-scale-in">
              {stats.map((stat, index) => (
                <div
                  key={stat.label}
                  className={`glassmorphism p-6 rounded-xl card-hover ${
                    currentStat === index ? "ring-2 ring-primary-500/50 animate-glow" : ""
                  }`}
                >
                  <stat.icon className={`w-8 h-8 ${stat.color} mx-auto mb-3`} />
                  <div className="text-2xl font-bold text-white mb-1">{stat.value}</div>
                  <div className="text-sm text-gray-400">{stat.label}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-dark-800/50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-5xl font-cyber font-bold text-gradient mb-6">Why Choose HashQuest?</h2>
            <p className="text-xl text-gray-300 max-w-3xl mx-auto">
              Experience the future of trivia gaming with cutting-edge technology and real rewards.
            </p>
          </div>

          <div className="responsive-grid">
            {features.map((feature, index) => (
              <div key={feature.title} className="animate-fade-in" style={{ animationDelay: `${index * 0.1}s` }}>
                <Card className="glassmorphism border-primary-500/20 hover:border-primary-500/40 card-hover h-full">
                  <CardContent className="p-6">
                    <feature.icon className={`w-12 h-12 ${feature.color} mb-4`} />
                    <h3 className="text-xl font-semibold text-white mb-3">{feature.title}</h3>
                    <p className="text-gray-300 leading-relaxed">{feature.description}</p>
                  </CardContent>
                </Card>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Categories Section - REMOVED */}

      {/* CTA Section */}
      <section className="py-20 bg-purple-gradient">
        {" "}
        {/* Changed from bg-cyber-gradient to bg-purple-gradient */}
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="animate-fade-in">
            <h2 className="text-3xl md:text-5xl font-cyber font-bold text-white mb-6">Ready to Start Earning?</h2>
            <p className="text-xl text-white/90 mb-8 max-w-2xl mx-auto">
              Join thousands of players already earning HBAR rewards through knowledge and skill.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link href="/auth/signup">
                <Button
                  size="lg"
                  variant="ghost"
                  className="bg-purple-gradient text-white text-lg px-8 py-4 hover:shadow-xl hover:shadow-purple-500/25 group"
                >
                  <Star className="w-6 h-6 mr-2" />
                  Create Account
                </Button>
              </Link>
              <Link href="/leaderboard">
                <Button
                  size="lg"
                  variant="ghost"
                  className="bg-purple-gradient text-white text-lg px-8 py-4 hover:shadow-xl hover:shadow-purple-500/25 group"
                >
                  <Award className="w-6 h-6 mr-2 group-hover:scale-110 transition-transform" />
                  View Leaderboard
                  <ChevronRight className="w-5 h-5 ml-2 group-hover:translate-x-1 transition-transform" />
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-dark-900 py-12 border-t border-primary-500/20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col md:flex-row justify-between items-center">
            <div className="flex items-center space-x-2 mb-4 md:mb-0">
              <div className="w-8 h-8 bg-cyber-gradient rounded-lg flex items-center justify-center">
                <span className="text-white font-bold text-lg">H</span>
              </div>
              <span className="font-cyber font-bold text-xl text-gradient">HashQuest</span>
            </div>
            <div className="flex space-x-6 text-gray-400">
              <Link href="/privacy" className="hover:text-primary-400 transition-colors">
                Privacy
              </Link>
              <Link href="/terms" className="hover:text-primary-400 transition-colors">
                Terms
              </Link>
              <Link href="/support" className="hover:text-primary-400 transition-colors">
                Support
              </Link>
            </div>
          </div>
          <div className="mt-8 pt-8 border-t border-gray-800 text-center text-gray-400">
            <p>&copy; 2024 HashQuest. All rights reserved. Built on Hedera Network.</p>
          </div>
        </div>
      </footer>
    </div>
  )
}
